<!--------------------------------------------
owned by nginxDEX

--------------------------------------------->
<html>

<title>Sh0ot</title>
<link rel="SHORTCUT ICON" href="https://blog.rootshell.be/wp-content/uploads/2012/02/blackhat-nl.png">
	<link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Iceberg' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Grand%20Hotel' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Graduate' rel='stylesheet' type='text/css'>
<iframe width="0%" height="0" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/45719017&amp;auto_play=true&amp;hide_related=ture&amp;show_comments=true&amp;show_user=false&amp;show_reposts=false&amp;visual=false"></iframe>
<br><br><br><br>
<center>
<pre style="font: 6px/3px monospace;"><span style="color: #ffffff;"></span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #e1c2c2;">#</span><span style="color: #830000;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #d6acac;">#</span><span style="color: #810000;">#</span><span style="color: #840000;">#</span><span style="color: #850000;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">###################</span><span style="color: #972828;">#</span><span style="color: #800000;">#</span><span style="color: #830000;">#</span><span style="color: #870000;">#</span><span style="color: #ffffff;">#################</span><span style="color: #ba7272;">#</span><span style="color: #a14242;">#</span><span style="color: #ffffff;">##################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##################</span><span style="color: #850000;">#</span><span style="color: #810000;">#</span><span style="color: #820000;">#</span><span style="color: #850000;">#</span><span style="color: #ffffff;">##################</span><span style="color: #850000;">#</span><span style="color: #830000;">#</span><span style="color: #800000;">#</span><span style="color: #ffffff;">#################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#################</span><span style="color: #850000;">#</span><span style="color: #820000;">#</span><span style="color: #800000;">#</span><span style="color: #830000;">#</span><span style="color: #efdede;">#</span><span style="color: #ffffff;">###################</span><span style="color: #860000;">#</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #ffffff;">################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">################</span><span style="color: #880000;">#</span><span style="color: #830000;">#</span><span style="color: #800000;">##</span><span style="color: #830000;">#</span><span style="color: #ffffff;">####################</span><span style="color: #c98c8c;">#</span><span style="color: #830000;">#</span><span style="color: #820000;">#</span><span style="color: #a03636;">#</span><span style="color: #ffffff;">###############
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">###############</span><span style="color: #9c2828;">#</span><span style="color: #850000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">##</span><span style="color: #820000;">#</span><span style="color: #ffffff;">###</span><span style="color: #f2e4e4;">#</span><span style="color: #a64c4c;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">##</span><span style="color: #810000;">#</span><span style="color: #a94e4e;">#</span><span style="color: #f8f0f0;">#</span><span style="color: #ffffff;">##########</span><span style="color: #830000;">#</span><span style="color: #800000;">#</span><span style="color: #850000;">#</span><span style="color: #f2e2e2;">#</span><span style="color: #ffffff;">##############
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##############</span><span style="color: #e7caca;">#</span><span style="color: #870000;">#</span><span style="color: #830000;">#</span><span style="color: #800000;">###</span><span style="color: #810000;">#</span><span style="color: #f2e4e4;">#</span><span style="color: #a04040;">#</span><span style="color: #800000;">#######</span><span style="color: #810000;">#</span><span style="color: #820000;">#</span><span style="color: #830000;">#</span><span style="color: #b56464;">#</span><span style="color: #ffffff;">########</span><span style="color: #830000;">#</span><span style="color: #800000;">#</span><span style="color: #830000;">#</span><span style="color: #890000;">#</span><span style="color: #ffffff;">##############
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##############</span><span style="color: #8d0000;">#</span><span style="color: #850000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">###############</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #850000;">#</span><span style="color: #f6ecec;">#</span><span style="color: #ffffff;">#####</span><span style="color: #d8aeae;">#</span><span style="color: #820000;">#</span><span style="color: #800000;">#</span><span style="color: #820000;">#</span><span style="color: #870000;">#</span><span style="color: #ffffff;">##############
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##############</span><span style="color: #8b0000;">#</span><span style="color: #840000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #840000;">#</span><span style="color: #e5c8c8;">#</span><span style="color: #ffffff;">###</span><span style="color: #e4c6c6;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#</span><span style="color: #810000;">#</span><span style="color: #850000;">#</span><span style="color: #ba6666;">#</span><span style="color: #ffffff;">#############
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##############</span><span style="color: #8a0000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#################</span><span style="color: #810000;">##</span><span style="color: #820000;">#</span><span style="color: #ffffff;">#</span><span style="color: #cb9696;">#</span><span style="color: #820000;">##</span><span style="color: #810000;">#</span><span style="color: #800000;">##</span><span style="color: #810000;">#</span><span style="color: #850000;">#</span><span style="color: #8d0000;">#</span><span style="color: #ffffff;">#############
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##############</span><span style="color: #8b0000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">###########################</span><span style="color: #810000;">#</span><span style="color: #840000;">#</span><span style="color: #8c0000;">#</span><span style="color: #ffffff;">#############
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##############</span><span style="color: #8b0000;">#</span><span style="color: #840000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">###########################</span><span style="color: #810000;">#</span><span style="color: #850000;">#</span><span style="color: #8d0000;">#</span><span style="color: #ffffff;">#############
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##############</span><span style="color: #a94242;">#</span><span style="color: #840000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">###########################</span><span style="color: #820000;">#</span><span style="color: #860000;">#</span><span style="color: #941010;">#</span><span style="color: #ffffff;">#############
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##############</span><span style="color: #f1e0e0;">#</span><span style="color: #850000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">##########################</span><span style="color: #810000;">#</span><span style="color: #840000;">#</span><span style="color: #890000;">#</span><span style="color: #ffffff;">##############
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">###############</span><span style="color: #850000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#########################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #860000;">#</span><span style="color: #e0baba;">#</span><span style="color: #ffffff;">##############
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##############</span><span style="color: #e8cccc;">#</span><span style="color: #850000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">########################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #850000;">#</span><span style="color: #bf7474;">#</span><span style="color: #ffffff;">###############
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##############</span><span style="color: #a03030;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#######################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #850000;">#</span><span style="color: #c88888;">#</span><span style="color: #ffffff;">################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##############</span><span style="color: #880000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">######################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #850000;">#</span><span style="color: #f0dede;">#</span><span style="color: #ffffff;">#################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##############</span><span style="color: #850000;">#</span><span style="color: #820000;">#</span><span style="color: #800000;">######################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #860000;">#</span><span style="color: #ffffff;">###################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#############</span><span style="color: #962020;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">######################</span><span style="color: #820000;">#</span><span style="color: #850000;">#</span><span style="color: #ffffff;">####################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">############</span><span style="color: #a63e3e;">#</span><span style="color: #850000;">#</span><span style="color: #820000;">#</span><span style="color: #800000;">######################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #a03434;">#</span><span style="color: #ffffff;">####################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">###########</span><span style="color: #e5c6c6;">#</span><span style="color: #860000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">######################</span><span style="color: #810000;">#</span><span style="color: #850000;">#</span><span style="color: #c68282;">#</span><span style="color: #ffffff;">####################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">######</span><span style="color: #c48888;">#</span><span style="color: #ffffff;">####</span><span style="color: #880000;">#</span><span style="color: #840000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#######################</span><span style="color: #820000;">#</span><span style="color: #860000;">#</span><span style="color: #f1e0e0;">#</span><span style="color: #ffffff;">####################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">######</span><span style="color: #dcb8b8;">#</span><span style="color: #840000;">#</span><span style="color: #850000;">#</span><span style="color: #ffffff;">##</span><span style="color: #850000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">######################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #880000;">#</span><span style="color: #ffffff;">#####################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#######</span><span style="color: #850000;">#</span><span style="color: #840000;">##</span><span style="color: #972a2a;">##</span><span style="color: #820000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">######################</span><span style="color: #810000;">#</span><span style="color: #840000;">#</span><span style="color: #8b0000;">#</span><span style="color: #ffffff;">#####################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#######</span><span style="color: #e9d2d2;">#</span><span style="color: #830000;">###</span><span style="color: #fdfafa;">#</span><span style="color: #820000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#####################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #860000;">#</span><span style="color: #e7caca;">#</span><span style="color: #ffffff;">#####################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">####</span><span style="color: #850000;">#</span><span style="color: #a44242;">#</span><span style="color: #fdfafa;">#</span><span style="color: #ffffff;">##</span><span style="color: #c58a8a;">#</span><span style="color: #810000;">#</span><span style="color: #ffffff;">#</span><span style="color: #901e1e;">#</span><span style="color: #810000;">##</span><span style="color: #800000;">####################</span><span style="color: #810000;">#</span><span style="color: #840000;">#</span><span style="color: #8a0000;">#</span><span style="color: #ffffff;">######################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">####</span><span style="color: #850000;">###</span><span style="color: #ffffff;">###</span><span style="color: #800000;">#</span><span style="color: #a24444;">#</span><span style="color: #ffffff;">#</span><span style="color: #9c3636;">#</span><span style="color: #810000;">###</span><span style="color: #800000;">#################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #880000;">#</span><span style="color: #ffffff;">#######################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">####</span><span style="color: #e2c2c2;">#</span><span style="color: #840000;">#</span><span style="color: #850000;">#</span><span style="color: #830000;">#</span><span style="color: #ebd6d6;">#</span><span style="color: #ffffff;">#</span><span style="color: #800000;">#</span><span style="color: #9f3e3e;">#</span><span style="color: #ffffff;">###</span><span style="color: #8a1212;">#</span><span style="color: #810000;">##</span><span style="color: #800000;">###############</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #850000;">#</span><span style="color: #d19a9a;">#</span><span style="color: #ffffff;">#######################
</span><span style="color: #ffffff;">#</span><span style="color: #830000;">#</span><span style="color: #f0e0e0;">#</span><span style="color: #ffffff;">#####</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">##</span><span style="color: #d9b2b2;">#</span><span style="color: #ffffff;">#####</span><span style="color: #ba7474;">#</span><span style="color: #810000;">##</span><span style="color: #800000;">#############</span><span style="color: #820000;">#</span><span style="color: #850000;">#</span><span style="color: #d7a8a8;">#</span><span style="color: #ffffff;">########################
</span><span style="color: #ffffff;">#</span><span style="color: #880a0a;">#</span><span style="color: #850000;">#</span><span style="color: #830000;">#</span><span style="color: #a64a4a;">#</span><span style="color: #ffffff;">####</span><span style="color: #810000;">#</span><span style="color: #800000;">##</span><span style="color: #dcb8b8;">#</span><span style="color: #ffffff;">#</span><span style="color: #b97272;">#</span><span style="color: #800000;">##</span><span style="color: #dab4b4;">#</span><span style="color: #ffffff;">##</span><span style="color: #820000;">##</span><span style="color: #810000;">#</span><span style="color: #800000;">##########</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #f8f0f0;">#</span><span style="color: #ffffff;">#########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #850000;">#</span><span style="color: #830000;">#</span><span style="color: #9b3434;">#</span><span style="color: #ffffff;">##</span><span style="color: #e3c6c6;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">###</span><span style="color: #800000;">####</span><span style="color: #810000;">#</span><span style="color: #820000;">#</span><span style="color: #d8b0b0;">#</span><span style="color: #ffffff;">##</span><span style="color: #eddada;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#########</span><span style="color: #810000;">#</span><span style="color: #850000;">#</span><span style="color: #ffffff;">##########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#</span><span style="color: #c07c7c;">#</span><span style="color: #840000;">#</span><span style="color: #830000;">#</span><span style="color: #820000;">#</span><span style="color: #810000;">##</span><span style="color: #820000;">##</span><span style="color: #ffffff;">#</span><span style="color: #830000;">#</span><span style="color: #820000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">##</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #982c2c;">#</span><span style="color: #ffffff;">###</span><span style="color: #e7cece;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#########</span><span style="color: #810000;">#</span><span style="color: #850000;">#</span><span style="color: #ffffff;">##########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">###</span><span style="color: #e1c2c2;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#</span><span style="color: #a34646;">#</span><span style="color: #faf4f4;">#</span><span style="color: #ffffff;">###</span><span style="color: #e5caca;">#</span><span style="color: #820000;">#</span><span style="color: #800000;">###</span><span style="color: #820000;">#</span><span style="color: #ffffff;">####</span><span style="color: #c99090;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#########</span><span style="color: #810000;">#</span><span style="color: #850000;">#</span><span style="color: #ffffff;">##########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">###########</span><span style="color: #d9b0b0;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">##</span><span style="color: #810000;">##</span><span style="color: #962c2c;">#</span><span style="color: #cc9898;">#</span><span style="color: #a34646;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">##########</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #8a0000;">#</span><span style="color: #ffffff;">#########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">###########</span><span style="color: #890000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">##################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #870000;">#</span><span style="color: #fefcfc;">#</span><span style="color: #ffffff;">########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">###########</span><span style="color: #8b0000;">#</span><span style="color: #850000;">#</span><span style="color: #820000;">#</span><span style="color: #800000;">###################</span><span style="color: #820000;">#</span><span style="color: #850000;">#</span><span style="color: #a53636;">#</span><span style="color: #ffffff;">########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">###########</span><span style="color: #a02c2c;">#</span><span style="color: #880000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">##################</span><span style="color: #810000;">#</span><span style="color: #840000;">#</span><span style="color: #8b0000;">#</span><span style="color: #ffffff;">########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#############</span><span style="color: #860000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #8a0000;">#</span><span style="color: #ffffff;">########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#############</span><span style="color: #cf9898;">#</span><span style="color: #860000;">#</span><span style="color: #830000;">#</span><span style="color: #820000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">###############</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #890000;">#</span><span style="color: #ffffff;">########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">################</span><span style="color: #8b0e0e;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">##############</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #890000;">#</span><span style="color: #ffffff;">########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#################</span><span style="color: #c98e8e;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#############</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #8a0000;">#</span><span style="color: #ffffff;">########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##################</span><span style="color: #850000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#############</span><span style="color: #810000;">#</span><span style="color: #840000;">#</span><span style="color: #9f2c2c;">#</span><span style="color: #ffffff;">########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##################</span><span style="color: #870000;">#</span><span style="color: #830000;">#</span><span style="color: #800000;">#############</span><span style="color: #810000;">#</span><span style="color: #850000;">#</span><span style="color: #ffffff;">#########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##################</span><span style="color: #890000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">############</span><span style="color: #810000;">#</span><span style="color: #840000;">#</span><span style="color: #f9f2f2;">#</span><span style="color: #ffffff;">########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##################</span><span style="color: #8a0000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">############</span><span style="color: #810000;">#</span><span style="color: #840000;">#</span><span style="color: #bf7272;">#</span><span style="color: #ffffff;">########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##################</span><span style="color: #8c0000;">#</span><span style="color: #840000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">############</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #880000;">#</span><span style="color: #ffffff;">########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##################</span><span style="color: #b55a5a;">#</span><span style="color: #850000;">#</span><span style="color: #820000;">#</span><span style="color: #800000;">#############</span><span style="color: #820000;">#</span><span style="color: #850000;">#</span><span style="color: #ffffff;">########################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">###################</span><span style="color: #880000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">############</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #a64242;">#</span><span style="color: #ffffff;">#######################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">###################</span><span style="color: #a03030;">#</span><span style="color: #850000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#############</span><span style="color: #820000;">#</span><span style="color: #850000;">#</span><span style="color: #d6a6a6;">#</span><span style="color: #ffffff;">######################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">####################</span><span style="color: #860000;">#</span><span style="color: #820000;">#</span><span style="color: #800000;">#############</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #850000;">#</span><span style="color: #f7eeee;">#</span><span style="color: #ffffff;">#####################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">####################</span><span style="color: #f1e2e2;">#</span><span style="color: #820000;">#</span><span style="color: #800000;">##############</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #850000;">#</span><span style="color: #ebd4d4;">#</span><span style="color: #ffffff;">####################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">####################</span><span style="color: #850000;">#</span><span style="color: #820000;">#</span><span style="color: #800000;">##############</span><span style="color: #810000;">##</span><span style="color: #830000;">#</span><span style="color: #840000;">#</span><span style="color: #a64646;">#</span><span style="color: #ffffff;">###################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">####################</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#############</span><span style="color: #d2a4a4;">#</span><span style="color: #810000;">###</span><span style="color: #820000;">#</span><span style="color: #830000;">#</span><span style="color: #840000;">#</span><span style="color: #c17e7e;">#</span><span style="color: #ffffff;">#################
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">##################</span><span style="color: #d1a0a0;">#</span><span style="color: #830000;">#</span><span style="color: #820000;">#</span><span style="color: #800000;">#############</span><span style="color: #810000;">#</span><span style="color: #ffffff;">##</span><span style="color: #bb7676;">#</span><span style="color: #800000;">###</span><span style="color: #810000;">#</span><span style="color: #820000;">#</span><span style="color: #830000;">##</span><span style="color: #debcbc;">#</span><span style="color: #ffffff;">##############
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">########</span><span style="color: #f2e4e4;">#</span><span style="color: #ac5656;">#</span><span style="color: #820000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">###</span><span style="color: #810000;">#####</span><span style="color: #800000;">#############</span><span style="color: #810000;">#</span><span style="color: #820000;">#</span><span style="color: #e1c0c0;">#</span><span style="color: #ffffff;">###</span><span style="color: #f0e0e0;">#</span><span style="color: #820000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">##</span><span style="color: #810000;">######</span><span style="color: #870e0e;">#</span><span style="color: #ba7474;">#</span><span style="color: #f6ecec;">#</span><span style="color: #ffffff;">#######
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">######</span><span style="color: #c37e7e;">#</span><span style="color: #850000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#######################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #9c2c2c;">#</span><span style="color: #ffffff;">######</span><span style="color: #e5caca;">#</span><span style="color: #8d1a1a;">#</span><span style="color: #800000;">#########</span><span style="color: #810000;">##</span><span style="color: #c07e7e;">#</span><span style="color: #ffffff;">####
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">####</span><span style="color: #edd8d8;">#</span><span style="color: #8b0000;">#</span><span style="color: #860000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">########################</span><span style="color: #810000;">#</span><span style="color: #840000;">#</span><span style="color: #8a0000;">#</span><span style="color: #ffffff;">###########</span><span style="color: #fcf8f8;">#</span><span style="color: #dab4b4;">#</span><span style="color: #ba7474;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#####</span><span style="color: #820000;">#</span><span style="color: #911c1c;">#</span><span style="color: #ffffff;">##
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">####</span><span style="color: #e1bebe;">#</span><span style="color: #8b0000;">#</span><span style="color: #850000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#######################</span><span style="color: #810000;">#</span><span style="color: #830000;">#</span><span style="color: #850000;">#</span><span style="color: #8c0000;">#</span><span style="color: #ffffff;">##################</span><span style="color: #d1a0a0;">#</span><span style="color: #820000;">#</span><span style="color: #800000;">#</span><span style="color: #830000;">#</span><span style="color: #860000;">#</span><span style="color: #ffffff;">#
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#####</span><span style="color: #8a0000;">#</span><span style="color: #860000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#######################</span><span style="color: #820000;">#</span><span style="color: #840000;">#</span><span style="color: #880000;">#</span><span style="color: #bf7474;">#</span><span style="color: #ffffff;">####################</span><span style="color: #b36666;">#</span><span style="color: #810000;">#</span><span style="color: #850000;">#</span><span style="color: #8a0000;">#
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">######</span><span style="color: #a94a4a;">#</span><span style="color: #850000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">######</span><span style="color: #800000;">###############</span><span style="color: #810000;">#</span><span style="color: #820000;">#</span><span style="color: #840000;">#</span><span style="color: #b66464;">#</span><span style="color: #ffffff;">################</span><span style="color: #810000;">#</span><span style="color: #9a3434;">#</span><span style="color: #ffffff;">#####</span><span style="color: #810000;">#</span><span style="color: #850000;">#</span><span style="color: #8a0000;">#
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#############</span><span style="color: #d2a2a2;">#</span><span style="color: #830000;">#</span><span style="color: #820000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">##########</span><span style="color: #810000;">##</span><span style="color: #820000;">#</span><span style="color: #ab5252;">#</span><span style="color: #ebd6d6;">#</span><span style="color: #ffffff;">################</span><span style="color: #b96e6e;">#</span><span style="color: #830000;">#</span><span style="color: #800000;">#</span><span style="color: #810000;">#</span><span style="color: #fcf8f8;">#</span><span style="color: #ffffff;">##</span><span style="color: #d6acac;">#</span><span style="color: #810000;">##</span><span style="color: #850000;">#</span><span style="color: #8a0000;">#
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">###############</span><span style="color: #c68a8a;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#####</span><span style="color: #810000;">##</span><span style="color: #a64c4c;">#</span><span style="color: #d1a2a2;">#</span><span style="color: #fcf8f8;">#</span><span style="color: #ffffff;">###################</span><span style="color: #870000;">#</span><span style="color: #840000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#</span><span style="color: #810000;">#</span><span style="color: #820000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">###</span><span style="color: #830000;">#</span><span style="color: #860000;">#</span><span style="color: #ffffff;">#
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">#############################################</span><span style="color: #931a1a;">#</span><span style="color: #880000;">#</span><span style="color: #850000;">#</span><span style="color: #830000;">#</span><span style="color: #810000;">#</span><span style="color: #800000;">#</span><span style="color: #810000;">#</span><span style="color: #830000;">###</span><span style="color: #820000;">#</span><span style="color: #a54646;">#</span><span style="color: #efdede;">#</span><span style="color: #ffffff;">##
</span><span style="color: #ffffff;">#</span><span style="color: #ffffff;">###########################################</span><span style="color: #932424;">#</span><span style="color: #830000;">#</span><span style="color: #850000;">##</span><span style="color: #840000;">#</span><span style="color: #830000;">#</span><span style="color: #800000;">##</span><span style="color: #820000;">#</span><span style="color: #ba7272;">#</span><span style="color: #f5eaea;">#</span><span style="color: #ffffff;">######
</span></pre>
<center><font size='7'color='black' face='Iceberg' style='text-shadow: 100px 0px 30px _blank;'> Cod3name  - nginxDEX </font></center>
<center><font face="Kaushan Script"><font color='gray' style='text-shadow: 5px 0px 30px _blank;'<font size="5"> Magelang6etar - CowoKerensTeam ~ IndoXploit  Magelang ~ All indonesia Defacer </div></font></center>
<p>


</PRE></font></center>
<center><table align=center style="color:white;font-size:18px;font-family:iceberg;text-shadow: 0 0 6px #FF0000, 0 0 5px #FF0000, 0 0 5px #FF0000;"><tr><td><center><br>
 
<body>
<body bgcolor="#202020">
<body oncontextmenu='return false;' onkeydown='return false;' onmousedown='return false;'></body>
<!-- --------Cursor--------- --><style type="text/css">body, a:hover {cursor: url(http://cur.cursors-4u.net/symbols/sym-1/sym46.cur), progress !important;}</style><a href="" target="blank" ><img src="http://cur.cursors-4u.net/cursor.png" 
border="0" style="position:absolute; top: 0px; right: 0px;" /></a>

<style>body{overflow:hidden;background-color:white}#q{font:20px impact;color:white;position:absolute;left:0;right:0;top:43%}

<!-- #Editing >> nginxDEX-->
<!-- #Source >> Lock-Down -->